


Top:
  Fpga[:]: # "[:]" is a wildcard for a dict search
    ##########################################################################
    Asic: # Note: Configuration tuned for ASIC Board V2: #6
      ##########################################################################
      Gpio:
        RSTB_RAM: 0x1
        RST_COUNTER: 0x0
        DlyCalPulseSet: 2450 # Rising edge of EXT_TRIG
        DlyCalPulseReset: 0 # Falling edge of EXT_TRIG
      TdcClk:
        Tdc40MHzClkSel: Pll
        FpgaTdcClkHigh: 0x1
        FpgaTdcClkLow: 0x1
      Trig:
        enable: True
        TrigTypeSel: Master
        CalStrobeAlign: 0x3      # Same as calibration pulse testing
        TrigStrobeAlign: 0x3     # Sets 6.25 ns trigger window w.r.t to 40 MHz clock  (might need tuning for the real system)
        EnCalPulseTrig: 0x1      # Disable calibration pulse
        EnBncExtTrig: 0x0        # Disable BNC external trigger
        EnPcieLocalTrig: 0x0     # Enable the local TOA_BUSY trigger
        EnLemoRemoteTrig: 0x0    # Enable the remote TOA_BUSY trigger   
        MasterModeSel: OR        # Either OR or AND the TOA_BUSY triggers together (inverted to active HIGH logic in FW)
        ReadoutStartDly: 128     # Units of 6.4ns (might need tuning for the real system)
        TrigSizeBeforePause: 0x0 # number of triggers before o-scope deadtime (zero bypass deadtime
        DeadtimeDuration: 0x0    # number of seconds to hold off readout until o-scope recovers
        EnableReadout: 0x1       # prevents either o-scope or dataStream from receiving data until enabled
      ##########################################################################
      SlowControl:
        ########################
        #general settings -> all off
        EN_ck_SRAM[:]: 0x1
        ON_Ctest[:]: 0x0
        disable_pa[:]: 0x0
        ON_discri[:]: 0x0
        bit_vth_cor[:]: 0x40       
        DAC10bit: 320

        #chON
        bit_vth_cor[11]: 70   #320 5 0
        bit_vth_cor[12]: 31   #320 5 0
        bit_vth_cor[14]: 71   #320 5 0
        bit_vth_cor[15]: 95   #320 5 0
        bit_vth_cor[16]: 34   #320 5 0
        bit_vth_cor[17]: 45   #320 5 0
        bit_vth_cor[19]: 92   #320 5 0
        bit_vth_cor[1]: 30   #320 5 0
        bit_vth_cor[20]: 74   #320 5 0
        bit_vth_cor[21]: 74   #320 5 0
        bit_vth_cor[22]: 87   #320 5 0
        bit_vth_cor[23]: 82   #320 5 0
        bit_vth_cor[24]: 80   #320 5 0
        bit_vth_cor[2]: 49   #320 5 0
        bit_vth_cor[4]: 104   #320 5 0
        bit_vth_cor[5]: 79   #320 5 0
        bit_vth_cor[6]: 20   #320 5 0
        bit_vth_cor[8]: 33   #320 5 0


        # bit_vth_cor[0]: 54   #320 4 0
        # bit_vth_cor[11]: 99   #320 4 0
        # bit_vth_cor[12]: 38   #320 4 0
        # bit_vth_cor[14]: 99   #320 4 0
        # bit_vth_cor[15]: 99   #320 4 0
        # bit_vth_cor[16]: 41   #320 4 0
        # bit_vth_cor[17]: 51   #320 4 0
        # bit_vth_cor[19]: 99   #320 4 0
        # bit_vth_cor[1]: 37   #320 4 0
        # bit_vth_cor[20]: 76   #320 4 0
        # bit_vth_cor[21]: 76   #320 4 0
        # bit_vth_cor[22]: 89   #320 4 0
        # bit_vth_cor[23]: 84   #320 4 0
        # bit_vth_cor[24]: 99   #320 4 0
        # bit_vth_cor[2]: 55   #320 4 0
        # bit_vth_cor[4]: 107   #320 4 0
        # bit_vth_cor[5]: 82   #320 4 0
        # bit_vth_cor[6]: 29   #320 4 0
        # bit_vth_cor[8]: 42   #320 4 0

        bit_vth_cor[0]: 47   #320 5 0


        
      
        EN_hyst[:]: 0x1
        EN_trig_ext[:]: 0x0
        cBit_f_TOA[:]: 0x0   # increase to 0 to f to reduce LSB while keeping cBit_s_TOA=0        
        cBit_f_TOA[1]: 0x1
        cBit_f_TOA[12]: 0x1
        cBit_f_TOA[13]: 0x2
        cBit_f_TOA[14]: 0x1
        cBit_f_TOA[17]: 0x1
        cBit_f_TOA[18]: 0x1 
        cBit_s_TOA[0]: 0x0
        cBit_s_TOA[3]: 0x1
        cBit_s_TOA[4]: 0x1
        cBit_s_TOA[5]: 0x1
        cBit_s_TOA[9]: 0x1
        cBit_s_TOA[15]: 0x1
        cBit_s_TOA[19]: 0x1
        cBit_s_TOA[20]: 0x1
        cBit_s_TOA[22]: 0x1
        cBit_s_TOA[23]: 0x1
        cBit_f_TOT[:]: 0x0
        cBit_s_TOT[:]: 0x0
        cBit_c_TOT[:]: 0x0
        ###################

        DLL_ALockR_en: 0x1 # should be kept to 1
        DLL_CP_b: 0x10
        ON_ota_dll: 1
        DLLfast_EXTvctrl_en: 0x1
        DLLslow_EXTvctrl_en: 0x1 
        DLLcoarse_EXTvctrl_en: 0x1 

        coarse_Lcomp_b: 0 #63 # 6 bits
        coarse_Up_Downb: 0 # 1
        fast_Lcomp_b: 0 #63 # 6 bits
        fast_Up_Downb: 0 #1
        slow_Lcomp_b: 0 # 63 # 6 bits, B24 8
        slow_Up_Downb: 0 #1


        totf_satovfw: 0x1
        totc_satovfw: 0x1
        toac_satovfw: 0x1      
      
        SatFVa: 0x4 #3
        IntFVa: 0x0 #1
       
        cBitf: 0x0 # with R dividers cbitf 0, decrease from f to 0 to reduce LSB while increasing cBits to f 
        Cbits: 0x2 #
        Cbitc: 5 # with R dividers 0     

        ON_rtest: 0x0 # with 1 add  1kOhm in // 
        Rin_Vpa: 0x0 #0 0 => 25K, 1 => 20K.
        Cp_Vpa: 0x0

        cd[0]: 0x0 
        cd[1]: 0x0 
        cd[2]: 0x0
        cd[3]: 0x0
        cd[4]: 0x0 
   
        dac_biaspa: 30 #10
        #ON_dac_biaspa: 0x1
        dac_pulser: 12 
      

        ON_dac_LR: 0x0 #RPG
        choice_shifted_ck40: 0x0
        choice_fpga_ck40: 0x1
        EN_8drivers: 0x1

        ON_PLL: 0x0

        EN_toa_busy: 0


        ref_bg: 0x0


      ##########################################################################
      Readout:
        #####################
        RstRamPulseWidth: 0xF
        ProbeToRstDly: 0x0  # Min. tuned on 18JULY2019:LLR
        RstPulseWidth: 0xF
        RstToReadDly: 0x0   # Min. tuned on 18JULY2019:LLR
        RckHighWidth: 0x2   # Min. tuned on 18JULY2019:LLR
        RckLowWidth: 0x2    # Min. tuned on 18JULY2019:LLR
        #####################
        RestoreProbeConfig: 0x1 #1 sets probe in previous config
        EnProbeWrite: 0x1
        OnlySendFirstHit: 0x1
        #Probe cofiguration
        EnProbeDigOutDisc: 0x0
        EnProbeDigSelect: 0x0
        EnProbeDig: 0x0
        EnProbePa: 0x0
        #####################
        RdIndexLut[0]: 0
        RdIndexLut[1]: 1
        RdIndexLut[2]: 2
        RdIndexLut[3]: 3
        RdIndexLut[4]: 4
        RdIndexLut[5]: 5
        RdIndexLut[6]: 6
        RdIndexLut[7]: 7
        RdIndexLut[8]: 8
        RdIndexLut[9]: 9
        RdIndexLut[10]: 10
        RdIndexLut[11]: 11
        RdIndexLut[12]: 12
        RdIndexLut[13]: 13
        RdIndexLut[14]: 14
        RdIndexLut[15]: 15
        RdIndexLut[16]: 16
        RdIndexLut[17]: 17
        RdIndexLut[18]: 18
        RdIndexLut[19]: 19
        RdIndexLut[20]: 20
        RdIndexLut[21]: 21
        RdIndexLut[22]: 22
        RdIndexLut[23]: 23
        RdIndexLut[24]: 24
        ReadoutSize: 0
  LiveDisplayRst: 0
