Top:
  Fpga[:]: # "[:]" is a wildcard for a dict search
    ##########################################################################
    Dac:
      RawValue:  0x8000
    ##########################################################################
    Asic:
      ##########################################################################
      Gpio:
        RSTB_RAM: 0x1
        RST_COUNTER: 0x0
        #RSTB_TDC: 0x1
        #RSTB_DLL: 0x1
        DlyCalPulseSet: 2450 # Rising edge of EXT_TRIG
        DlyCalPulseReset: 0xfff # Falling edge of EXT_TRIG
        ###########################################
      ##########################################################################
      TdcClk:
        Tdc40MHzClkSel: Pll
        FpgaTdcClkHigh: 0x1
        FpgaTdcClkLow: 0x1
      ##########################################################################
      CalPulse:
        CalPulseDelay: 0x32
        CalPulseCount: 0x0
        CalPulseWidth: 8
        Continuous: 0x0
      ##########################################################################
      Trig:
        enable: True
        TrigTypeSel: Master
        CalStrobeAlign: 0x3
        TrigStrobeAlign: 0x3
        EnCalPulseTrig: 0x0
        EnBncExtTrig: 0x0
        EnPcieLocalTrig: 0x0
        EnLemoRemoteTrig: 0x0
        MasterModeSel: OR
        ReadoutStartDly: 128 # Units of 6.4ns
        TrigSizeBeforePause: 0x0
        DeadtimeDuration: 0x0
        BusyPulseWidth: 255 # Units of 6.4ns
        EnableReadout: 0x0 # Disable triggers
        TrigWindowdbg: 0x0
        BncDebug: 0x0
      ##########################################################################
      SlowControl:
        dac: 0x0
        ON_dac_LR: 0x0
        Write_opt: 0x0
        Precharge_opt: 0x0
        ref_bg: 0x1
        dac_pulser: 60
        ON_rtest: 0x0
        Rin_Vpa: 0x0
        Cp_Vpa: 0x0
        dac_biaspa: 30
        ON_ota_dac: 0x1
        DAC10bit: 340
        SatFVa: 0x0
        IntFVa: 0x0
        EN_toa_busy: 0x0
        ON_ota_dll: 0x0
        EN_clps: 0x0
        totf_satovfw: 0x0
        cd[0]: 0x4
        cd[1]: 0x4
        cd[2]: 0x4
        cd[3]: 0x4
        cd[4]: 0x4
        choice_shifted_ck40: 0x0
        choice_fpga_ck40: 0x1
        cBitf: 0x0
        DLLfast_EXTvctrl_en: 0x0
        fast_Lcomp_b: 0x0
        fast_Up_Downb: 0x0
        DLL_CP_b: 0x10
        DLL_ALockR_en: 0x1
        Cbits: 0x0
        DLLslow_EXTvctrl_en: 0x0
        slow_Lcomp_b: 0x0
        slow_Up_Downb: 0x0
        Cbitc: 0x0
        DLLcoarse_EXTvctrl_en: 0x0
        coarse_Lcomp_b: 0x0
        coarse_Up_Downb: 0x0
        EN_8drivers: 0x1
        ON_PLL: 0x0
        PLL_icpb: 0x0A
        EN_RPG: 0x1
        dac_CP_BWb: 0x10
        EN_ExtVin_vco_PLL: 0x0
        setN: 0x3
        setProbe: 0x0
        EN_500: 0x0
        EN_1000: 0x0
        EN_2000: 0x1
        EN_4000: 0x0
        EN_200p: 0x0
        EN_LowKvco: 0x0
        FineDelay: 0x0
        CoarseDelay: 0x0
        p: 0x0
        forcedown: 0x0
        inita: 0x1
        initb: 0x1
        initc: 0x1
        cpen: 0x1
        PS_cp: 0x8
        En_40M: 0x0
        En_640M: 0x0
        FineDelayLum: 0x0
        detectEn: 0x0
        #####################
        EN_ck_SRAM[:]: 0x0
        ON_Ctest[:]: 0x0
        disable_pa[:]: 0x1
        bit_vth_cor[:]: 64
        ON_discri[:]: 0x0
        EN_hyst[:]: 0x1
        EN_trig_ext[:]: 0x0
        en_rstb_toa[:]: 0x0
        cBit_f_TOT[:]: 0x0
        cBit_c_TOT[:]: 0x0
        en_rstb_tot[:]: 0x0
        cBit_s_TOT[:]: 0x0
        cBit_s_TOA[:]: 0x0
        cBit_f_TOA[:]: 0x0


        
        ###################
        #turn ON single channel
        EN_ck_SRAM[1]: 0x1
        ON_Ctest[1]: 0x1
        disable_pa[1]: 0x0
        ON_discri[1]: 0x1
        bit_vth_cor[1]: 64
        ###################

        #####################
        rstL: 0x1


      ##########################################################################
      Probe:
        en_probe_dig: 0x1
        en_probe_pa: 0x1
        EN_dout: 0x0
        pix[1]:
            probe_pa: 0x1
            probe_dig_out_disc: 0x1
            probe_vthc: 0x0
            probe_toa: 0x0
            probe_tot: 0x0
            totf: 0x0
            tot_overflow: 0x0
            toa_busy: 0x0
            tot_busy: 0x0
            tot_ready: 0x0
            en_read: 0x1    #1 remove PA probe !?
 
      ##########################################################################
      Readout:
        ReadoutSize: 0
        RdIndexLut[0]: 1
        #####################
        RstRamPulseWidth: 0xF
        ProbeToRstDly: 0x0  # Min. tuned on 18JULY2019:LLR
        RstPulseWidth: 0xF
        RstToReadDly: 0x0   # Min. tuned on 18JULY2019:LLR
        RckHighWidth: 0x2   # Min. tuned on 18JULY2019:LLR
        RckLowWidth: 0x2    # Min. tuned on 18JULY2019:LLR
        #####################
        ProbeSclkConfig: 79 # 1MHz Probe SCLK
        RestoreProbeConfig: 0x1
        EnProbeWrite: 0x1
        OnlySendFirstHit: 0x1
        #####################
        #Probe cofiguration
        EnProbeDigOutDisc: 0x1
        EnProbeDigSelect: 0x0
        EnProbeDig: 0x1
        EnProbePa: 0x1

      ##########################################################################
