Top:
  enable: True
  ForceWrite: False
  StreamWriter:
    enable: True
    dataFile: ''
    open: False
    bufferSize: 0
    maxFileSize: 0
  AxiVersion:
    enable: True
    ScratchPad: 0x000000
    FpgaReloadHalt: 0x0
    FpgaReloadAddress: 0x0
    UserReset: 0x0
  Xadc:
    enable: True
  SysReg:
    enable: True
    DlyData: 0x0
    RefClkSel: IntClk
    RollOverEn: 0x0
  BoardTemp:
    enable: True
    AlertMask: False
    Stop: False
    RcritMask: False
    LcritMask: False
    FaultQueue: False
    ConvertRate: '16'
    LocalHighSetpoint: 70
    LocalLowSetpoint: 0
    RemoteHighSetpoint: 70
    RemoteLowSetpoint: 0
    RemoteTcritSetpoint: 85
    LocalTcritSetpoint: 85
    TcritHysteresis: 10
    AlertMode: False
  BoardPwr:
    enable: True
    Control: 0xc
  DelayIcTemp:
    enable: True
    AlertMask: True
    Stop: False
    RcritMask: False
    LcritMask: False
    FaultQueue: False
    ConvertRate: '16'
    LocalHighSetpoint: 70
    LocalLowSetpoint: 0
    RemoteHighSetpoint: 70
    RemoteLowSetpoint: 0
    RemoteTcritSetpoint: 85
    LocalTcritSetpoint: 85
    TcritHysteresis: 10
    AlertMode: False
  Dac:
    enable: True
    FloatValue: 0.000
  Asic:
    enable: True
    SlowControl:
      enable: True
      dac: 0x0
      ON_dac_LR: 0x0
      Write_opt: 0x0
      Precharge_opt: 0x0
      ref_bg: 0x1
      dac_pulser: 0x7
      Ccomp_TZ: 0x0
      Rin_Vpa: 0x0
      Cp_Vpa: 0x0
      dac_biaspa: 0x10
      ON_dac_biaspa: 0x0
      ON_ota_dac: 0x1
      DAC10bit: 0xdc
      SatFVa: 0x0
      IntFVa: 0x0
      SatFTz: 0x0
      IntFTz: 0x0
      totf_satovfw: 0x0
      totc_satovfw: 0x0
      toa_satovfw: 0x0
      ckw_choice: 0x0
      cBitf: 0x0
      DLL_ALockR_en: 0x0
      CP_b: 0x0
      ext_Vcrtlf_en: 0x0
      cBits: 0x0
      ext_Vcrtls_en: 0x0
      cBitc: 0x0
      ext_Vcrtlc_en: 0x0
      en_8drivers: 0x0
      EN_ck_SRAM[0]: 0x0
      ON_Ctest[0]: 0x0
      disable_pa[0]: 0x0
      bit_vth_cor[0]: 0x0
      ON_discri[0]: 0x0
      EN_hyst[0]: 0x0
      EN_trig_ext[0]: 0x0
      cBit_f_TOT[0]: 0x0
      cBit_c_TOT[0]: 0x0
      cBit_s_TOT[0]: 0x0
      cBit_s_TOA[0]: 0x0
      cBit_f_TOA[0]: 0x0
      EN_ck_SRAM[1]: 0x0
      ON_Ctest[1]: 0x0
      disable_pa[1]: 0x0
      bit_vth_cor[1]: 0x0
      ON_discri[1]: 0x0
      EN_hyst[1]: 0x0
      EN_trig_ext[1]: 0x0
      cBit_f_TOT[1]: 0x0
      cBit_c_TOT[1]: 0x0
      cBit_s_TOT[1]: 0x0
      cBit_s_TOA[1]: 0x0
      cBit_f_TOA[1]: 0x0
      EN_ck_SRAM[2]: 0x0
      ON_Ctest[2]: 0x0
      disable_pa[2]: 0x0
      bit_vth_cor[2]: 0x0
      ON_discri[2]: 0x0
      EN_hyst[2]: 0x0
      EN_trig_ext[2]: 0x0
      cBit_f_TOT[2]: 0x0
      cBit_c_TOT[2]: 0x0
      cBit_s_TOT[2]: 0x0
      cBit_s_TOA[2]: 0x0
      cBit_f_TOA[2]: 0x0
      EN_ck_SRAM[3]: 0x0
      ON_Ctest[3]: 0x0
      disable_pa[3]: 0x0
      bit_vth_cor[3]: 0x0
      ON_discri[3]: 0x0
      EN_hyst[3]: 0x0
      EN_trig_ext[3]: 0x0
      cBit_f_TOT[3]: 0x0
      cBit_c_TOT[3]: 0x0
      cBit_s_TOT[3]: 0x0
      cBit_s_TOA[3]: 0x0
      cBit_f_TOA[3]: 0x0
      EN_ck_SRAM[4]: 0x0
      ON_Ctest[4]: 0x1
      disable_pa[4]: 0x0
      bit_vth_cor[4]: 0x0
      ON_discri[4]: 0x1
      EN_hyst[4]: 0x1
      EN_trig_ext[4]: 0x0
      cBit_f_TOT[4]: 0x0
      cBit_c_TOT[4]: 0x0
      cBit_s_TOT[4]: 0x0
      cBit_s_TOA[4]: 0x0
      cBit_f_TOA[4]: 0x0
      EN_ck_SRAM[5]: 0x0
      ON_Ctest[5]: 0x0
      disable_pa[5]: 0x0
      bit_vth_cor[5]: 0x0
      ON_discri[5]: 0x0
      EN_hyst[5]: 0x0
      EN_trig_ext[5]: 0x0
      cBit_f_TOT[5]: 0x0
      cBit_c_TOT[5]: 0x0
      cBit_s_TOT[5]: 0x0
      cBit_s_TOA[5]: 0x0
      cBit_f_TOA[5]: 0x0
      EN_ck_SRAM[6]: 0x0
      ON_Ctest[6]: 0x0
      disable_pa[6]: 0x0
      bit_vth_cor[6]: 0x0
      ON_discri[6]: 0x0
      EN_hyst[6]: 0x0
      EN_trig_ext[6]: 0x0
      cBit_f_TOT[6]: 0x0
      cBit_c_TOT[6]: 0x0
      cBit_s_TOT[6]: 0x0
      cBit_s_TOA[6]: 0x0
      cBit_f_TOA[6]: 0x0
      EN_ck_SRAM[7]: 0x0
      ON_Ctest[7]: 0x0
      disable_pa[7]: 0x0
      bit_vth_cor[7]: 0x0
      ON_discri[7]: 0x0
      EN_hyst[7]: 0x0
      EN_trig_ext[7]: 0x0
      cBit_f_TOT[7]: 0x0
      cBit_c_TOT[7]: 0x0
      cBit_s_TOT[7]: 0x0
      cBit_s_TOA[7]: 0x0
      cBit_f_TOA[7]: 0x0
      EN_ck_SRAM[8]: 0x0
      ON_Ctest[8]: 0x0
      disable_pa[8]: 0x0
      bit_vth_cor[8]: 0x0
      ON_discri[8]: 0x0
      EN_hyst[8]: 0x0
      EN_trig_ext[8]: 0x0
      cBit_f_TOT[8]: 0x0
      cBit_c_TOT[8]: 0x0
      cBit_s_TOT[8]: 0x0
      cBit_s_TOA[8]: 0x0
      cBit_f_TOA[8]: 0x0
      EN_ck_SRAM[9]: 0x0
      ON_Ctest[9]: 0x0
      disable_pa[9]: 0x0
      bit_vth_cor[9]: 0x0
      ON_discri[9]: 0x0
      EN_hyst[9]: 0x0
      EN_trig_ext[9]: 0x0
      cBit_f_TOT[9]: 0x0
      cBit_c_TOT[9]: 0x0
      cBit_s_TOT[9]: 0x0
      cBit_s_TOA[9]: 0x0
      cBit_f_TOA[9]: 0x0
      EN_ck_SRAM[10]: 0x0
      ON_Ctest[10]: 0x0
      disable_pa[10]: 0x0
      bit_vth_cor[10]: 0x0
      ON_discri[10]: 0x0
      EN_hyst[10]: 0x0
      EN_trig_ext[10]: 0x0
      cBit_f_TOT[10]: 0x0
      cBit_c_TOT[10]: 0x0
      cBit_s_TOT[10]: 0x0
      cBit_s_TOA[10]: 0x0
      cBit_f_TOA[10]: 0x0
      EN_ck_SRAM[11]: 0x0
      ON_Ctest[11]: 0x0
      disable_pa[11]: 0x0
      bit_vth_cor[11]: 0x0
      ON_discri[11]: 0x0
      EN_hyst[11]: 0x0
      EN_trig_ext[11]: 0x0
      cBit_f_TOT[11]: 0x0
      cBit_c_TOT[11]: 0x0
      cBit_s_TOT[11]: 0x0
      cBit_s_TOA[11]: 0x0
      cBit_f_TOA[11]: 0x0
      EN_ck_SRAM[12]: 0x0
      ON_Ctest[12]: 0x0
      disable_pa[12]: 0x0
      bit_vth_cor[12]: 0x0
      ON_discri[12]: 0x0
      EN_hyst[12]: 0x0
      EN_trig_ext[12]: 0x0
      cBit_f_TOT[12]: 0x0
      cBit_c_TOT[12]: 0x0
      cBit_s_TOT[12]: 0x0
      cBit_s_TOA[12]: 0x0
      cBit_f_TOA[12]: 0x0
      EN_ck_SRAM[13]: 0x0
      ON_Ctest[13]: 0x0
      disable_pa[13]: 0x0
      bit_vth_cor[13]: 0x0
      ON_discri[13]: 0x0
      EN_hyst[13]: 0x0
      EN_trig_ext[13]: 0x0
      cBit_f_TOT[13]: 0x0
      cBit_c_TOT[13]: 0x0
      cBit_s_TOT[13]: 0x0
      cBit_s_TOA[13]: 0x0
      cBit_f_TOA[13]: 0x0
      EN_ck_SRAM[14]: 0x0
      ON_Ctest[14]: 0x0
      disable_pa[14]: 0x0
      bit_vth_cor[14]: 0x0
      ON_discri[14]: 0x0
      EN_hyst[14]: 0x0
      EN_trig_ext[14]: 0x0
      cBit_f_TOT[14]: 0x0
      cBit_c_TOT[14]: 0x0
      cBit_s_TOT[14]: 0x0
      cBit_s_TOA[14]: 0x0
      cBit_f_TOA[14]: 0x0
      EN_ck_SRAM[15]: 0x0
      ON_Ctest[15]: 0x0
      disable_pa[15]: 0x0
      bit_vth_cor[15]: 0x0
      ON_discri[15]: 0x0
      EN_hyst[15]: 0x0
      EN_trig_ext[15]: 0x0
      cBit_f_TOT[15]: 0x0
      cBit_c_TOT[15]: 0x0
      cBit_s_TOT[15]: 0x0
      cBit_s_TOA[15]: 0x0
      cBit_f_TOA[15]: 0x0
      EN_ck_SRAM[16]: 0x0
      ON_Ctest[16]: 0x0
      disable_pa[16]: 0x0
      bit_vth_cor[16]: 0x0
      ON_discri[16]: 0x0
      EN_hyst[16]: 0x0
      EN_trig_ext[16]: 0x0
      cBit_f_TOT[16]: 0x0
      cBit_c_TOT[16]: 0x0
      cBit_s_TOT[16]: 0x0
      cBit_s_TOA[16]: 0x0
      cBit_f_TOA[16]: 0x0
      EN_ck_SRAM[17]: 0x0
      ON_Ctest[17]: 0x0
      disable_pa[17]: 0x0
      bit_vth_cor[17]: 0x0
      ON_discri[17]: 0x0
      EN_hyst[17]: 0x0
      EN_trig_ext[17]: 0x0
      cBit_f_TOT[17]: 0x0
      cBit_c_TOT[17]: 0x0
      cBit_s_TOT[17]: 0x0
      cBit_s_TOA[17]: 0x0
      cBit_f_TOA[17]: 0x0
      EN_ck_SRAM[18]: 0x0
      ON_Ctest[18]: 0x0
      disable_pa[18]: 0x0
      bit_vth_cor[18]: 0x0
      ON_discri[18]: 0x0
      EN_hyst[18]: 0x0
      EN_trig_ext[18]: 0x0
      cBit_f_TOT[18]: 0x0
      cBit_c_TOT[18]: 0x0
      cBit_s_TOT[18]: 0x0
      cBit_s_TOA[18]: 0x0
      cBit_f_TOA[18]: 0x0
      EN_ck_SRAM[19]: 0x0
      ON_Ctest[19]: 0x0
      disable_pa[19]: 0x0
      bit_vth_cor[19]: 0x0
      ON_discri[19]: 0x0
      EN_hyst[19]: 0x0
      EN_trig_ext[19]: 0x0
      cBit_f_TOT[19]: 0x0
      cBit_c_TOT[19]: 0x0
      cBit_s_TOT[19]: 0x0
      cBit_s_TOA[19]: 0x0
      cBit_f_TOA[19]: 0x0
      EN_ck_SRAM[20]: 0x0
      ON_Ctest[20]: 0x0
      disable_pa[20]: 0x0
      bit_vth_cor[20]: 0x0
      ON_discri[20]: 0x0
      EN_hyst[20]: 0x0
      EN_trig_ext[20]: 0x0
      cBit_f_TOT[20]: 0x0
      cBit_c_TOT[20]: 0x0
      cBit_s_TOT[20]: 0x0
      cBit_s_TOA[20]: 0x0
      cBit_f_TOA[20]: 0x0
      EN_ck_SRAM[21]: 0x0
      ON_Ctest[21]: 0x0
      disable_pa[21]: 0x0
      bit_vth_cor[21]: 0x0
      ON_discri[21]: 0x0
      EN_hyst[21]: 0x0
      EN_trig_ext[21]: 0x0
      cBit_f_TOT[21]: 0x0
      cBit_c_TOT[21]: 0x0
      cBit_s_TOT[21]: 0x0
      cBit_s_TOA[21]: 0x0
      cBit_f_TOA[21]: 0x0
      EN_ck_SRAM[22]: 0x0
      ON_Ctest[22]: 0x0
      disable_pa[22]: 0x0
      bit_vth_cor[22]: 0x0
      ON_discri[22]: 0x0
      EN_hyst[22]: 0x0
      EN_trig_ext[22]: 0x0
      cBit_f_TOT[22]: 0x0
      cBit_c_TOT[22]: 0x0
      cBit_s_TOT[22]: 0x0
      cBit_s_TOA[22]: 0x0
      cBit_f_TOA[22]: 0x0
      EN_ck_SRAM[23]: 0x0
      ON_Ctest[23]: 0x0
      disable_pa[23]: 0x0
      bit_vth_cor[23]: 0x0
      ON_discri[23]: 0x0
      EN_hyst[23]: 0x0
      EN_trig_ext[23]: 0x0
      cBit_f_TOT[23]: 0x0
      cBit_c_TOT[23]: 0x0
      cBit_s_TOT[23]: 0x0
      cBit_s_TOA[23]: 0x0
      cBit_f_TOA[23]: 0x0
      EN_ck_SRAM[24]: 0x0
      ON_Ctest[24]: 0x0
      disable_pa[24]: 0x0
      bit_vth_cor[24]: 0x0
      ON_discri[24]: 0x0
      EN_hyst[24]: 0x0
      EN_trig_ext[24]: 0x0
      cBit_f_TOT[24]: 0x0
      cBit_c_TOT[24]: 0x0
      cBit_s_TOT[24]: 0x0
      cBit_s_TOA[24]: 0x0
      cBit_f_TOA[24]: 0x0
      cd[0]: 0x6
      cd[1]: 0x0
      cd[2]: 0x0
      cd[3]: 0x0
      cd[4]: 0x0
      PLL: 0x0
      dac_icpb: 0x0
      dac_CP_BWb: 0x0
      EN_Ext_Vin_VCO: 0x0
      setN: 0x0
      setProbe: 0x0
      EN_500: 0x0
      EN_1000: 0x0
      EN_2000: 0x0
      EN_4000: 0x0
      EN_200p: 0x0
      EN_LowKvco: 0x0
      delay: 0x0
      Ph: 0x0
      forcedown: 0x0
      inita: 0x0
      initb: 0x0
      initc: 0x0
      cpen: 0x0
      cp: 0x0
      En_40M: 0x0
      En_640M: 0x0
      rstL: 0x1
    Probe:
      enable: True
      en_probe_pa: 0x1
      en_probe_dig: 0x1
      EN_dout: 0x0
      probe_pa[0]: 0x0
      probe_vthc[0]: 0x0
      probe_dig_out_disc[0]: 0x0
      probe_toa[0]: 0x0
      probe_tot[0]: 0x0
      totf[0]: 0x0
      tot_overflow[0]: 0x0
      toa_busy[0]: 0x0
      toa_ready[0]: 0x0
      tot_busy[0]: 0x0
      tot_ready[0]: 0x0
      en_read[0]: 0x0
      probe_pa[1]: 0x0
      probe_vthc[1]: 0x0
      probe_dig_out_disc[1]: 0x0
      probe_toa[1]: 0x0
      probe_tot[1]: 0x0
      totf[1]: 0x0
      tot_overflow[1]: 0x0
      toa_busy[1]: 0x0
      toa_ready[1]: 0x0
      tot_busy[1]: 0x0
      tot_ready[1]: 0x0
      en_read[1]: 0x0
      probe_pa[2]: 0x0
      probe_vthc[2]: 0x0
      probe_dig_out_disc[2]: 0x0
      probe_toa[2]: 0x0
      probe_tot[2]: 0x0
      totf[2]: 0x0
      tot_overflow[2]: 0x0
      toa_busy[2]: 0x0
      toa_ready[2]: 0x0
      tot_busy[2]: 0x0
      tot_ready[2]: 0x0
      en_read[2]: 0x0
      probe_pa[3]: 0x0
      probe_vthc[3]: 0x0
      probe_dig_out_disc[3]: 0x0
      probe_toa[3]: 0x0
      probe_tot[3]: 0x0
      totf[3]: 0x0
      tot_overflow[3]: 0x0
      toa_busy[3]: 0x0
      toa_ready[3]: 0x0
      tot_busy[3]: 0x0
      tot_ready[3]: 0x0
      en_read[3]: 0x0
      probe_pa[4]: 0x1
      probe_vthc[4]: 0x0
      probe_dig_out_disc[4]: 0x1
      probe_toa[4]: 0x0
      probe_tot[4]: 0x0
      totf[4]: 0x0
      tot_overflow[4]: 0x0
      toa_busy[4]: 0x0
      toa_ready[4]: 0x0
      tot_busy[4]: 0x0
      tot_ready[4]: 0x0
      en_read[4]: 0x0
      probe_pa[5]: 0x0
      probe_vthc[5]: 0x0
      probe_dig_out_disc[5]: 0x0
      probe_toa[5]: 0x0
      probe_tot[5]: 0x0
      totf[5]: 0x0
      tot_overflow[5]: 0x0
      toa_busy[5]: 0x0
      toa_ready[5]: 0x0
      tot_busy[5]: 0x0
      tot_ready[5]: 0x0
      en_read[5]: 0x0
      probe_pa[6]: 0x0
      probe_vthc[6]: 0x0
      probe_dig_out_disc[6]: 0x0
      probe_toa[6]: 0x0
      probe_tot[6]: 0x0
      totf[6]: 0x0
      tot_overflow[6]: 0x0
      toa_busy[6]: 0x0
      toa_ready[6]: 0x0
      tot_busy[6]: 0x0
      tot_ready[6]: 0x0
      en_read[6]: 0x0
      probe_pa[7]: 0x0
      probe_vthc[7]: 0x0
      probe_dig_out_disc[7]: 0x0
      probe_toa[7]: 0x0
      probe_tot[7]: 0x0
      totf[7]: 0x0
      tot_overflow[7]: 0x0
      toa_busy[7]: 0x0
      toa_ready[7]: 0x0
      tot_busy[7]: 0x0
      tot_ready[7]: 0x0
      en_read[7]: 0x0
      probe_pa[8]: 0x0
      probe_vthc[8]: 0x0
      probe_dig_out_disc[8]: 0x0
      probe_toa[8]: 0x0
      probe_tot[8]: 0x0
      totf[8]: 0x0
      tot_overflow[8]: 0x0
      toa_busy[8]: 0x0
      toa_ready[8]: 0x0
      tot_busy[8]: 0x0
      tot_ready[8]: 0x0
      en_read[8]: 0x0
      probe_pa[9]: 0x0
      probe_vthc[9]: 0x0
      probe_dig_out_disc[9]: 0x0
      probe_toa[9]: 0x0
      probe_tot[9]: 0x0
      totf[9]: 0x0
      tot_overflow[9]: 0x0
      toa_busy[9]: 0x0
      toa_ready[9]: 0x0
      tot_busy[9]: 0x0
      tot_ready[9]: 0x0
      en_read[9]: 0x0
      probe_pa[10]: 0x0
      probe_vthc[10]: 0x0
      probe_dig_out_disc[10]: 0x0
      probe_toa[10]: 0x0
      probe_tot[10]: 0x0
      totf[10]: 0x0
      tot_overflow[10]: 0x0
      toa_busy[10]: 0x0
      toa_ready[10]: 0x0
      tot_busy[10]: 0x0
      tot_ready[10]: 0x0
      en_read[10]: 0x0
      probe_pa[11]: 0x0
      probe_vthc[11]: 0x0
      probe_dig_out_disc[11]: 0x0
      probe_toa[11]: 0x0
      probe_tot[11]: 0x0
      totf[11]: 0x0
      tot_overflow[11]: 0x0
      toa_busy[11]: 0x0
      toa_ready[11]: 0x0
      tot_busy[11]: 0x0
      tot_ready[11]: 0x0
      en_read[11]: 0x0
      probe_pa[12]: 0x0
      probe_vthc[12]: 0x0
      probe_dig_out_disc[12]: 0x0
      probe_toa[12]: 0x0
      probe_tot[12]: 0x0
      totf[12]: 0x0
      tot_overflow[12]: 0x0
      toa_busy[12]: 0x0
      toa_ready[12]: 0x0
      tot_busy[12]: 0x0
      tot_ready[12]: 0x0
      en_read[12]: 0x0
      probe_pa[13]: 0x0
      probe_vthc[13]: 0x0
      probe_dig_out_disc[13]: 0x0
      probe_toa[13]: 0x0
      probe_tot[13]: 0x0
      totf[13]: 0x0
      tot_overflow[13]: 0x0
      toa_busy[13]: 0x0
      toa_ready[13]: 0x0
      tot_busy[13]: 0x0
      tot_ready[13]: 0x0
      en_read[13]: 0x0
      probe_pa[14]: 0x0
      probe_vthc[14]: 0x0
      probe_dig_out_disc[14]: 0x0
      probe_toa[14]: 0x0
      probe_tot[14]: 0x0
      totf[14]: 0x0
      tot_overflow[14]: 0x0
      toa_busy[14]: 0x0
      toa_ready[14]: 0x0
      tot_busy[14]: 0x0
      tot_ready[14]: 0x0
      en_read[14]: 0x0
      probe_pa[15]: 0x0
      probe_vthc[15]: 0x0
      probe_dig_out_disc[15]: 0x0
      probe_toa[15]: 0x0
      probe_tot[15]: 0x0
      totf[15]: 0x0
      tot_overflow[15]: 0x0
      toa_busy[15]: 0x0
      toa_ready[15]: 0x0
      tot_busy[15]: 0x0
      tot_ready[15]: 0x0
      en_read[15]: 0x0
      probe_pa[16]: 0x0
      probe_vthc[16]: 0x0
      probe_dig_out_disc[16]: 0x0
      probe_toa[16]: 0x0
      probe_tot[16]: 0x0
      totf[16]: 0x0
      tot_overflow[16]: 0x0
      toa_busy[16]: 0x0
      toa_ready[16]: 0x0
      tot_busy[16]: 0x0
      tot_ready[16]: 0x0
      en_read[16]: 0x0
      probe_pa[17]: 0x0
      probe_vthc[17]: 0x0
      probe_dig_out_disc[17]: 0x0
      probe_toa[17]: 0x0
      probe_tot[17]: 0x0
      totf[17]: 0x0
      tot_overflow[17]: 0x0
      toa_busy[17]: 0x0
      toa_ready[17]: 0x0
      tot_busy[17]: 0x0
      tot_ready[17]: 0x0
      en_read[17]: 0x0
      probe_pa[18]: 0x0
      probe_vthc[18]: 0x0
      probe_dig_out_disc[18]: 0x0
      probe_toa[18]: 0x0
      probe_tot[18]: 0x0
      totf[18]: 0x0
      tot_overflow[18]: 0x0
      toa_busy[18]: 0x0
      toa_ready[18]: 0x0
      tot_busy[18]: 0x0
      tot_ready[18]: 0x0
      en_read[18]: 0x0
      probe_pa[19]: 0x0
      probe_vthc[19]: 0x0
      probe_dig_out_disc[19]: 0x0
      probe_toa[19]: 0x0
      probe_tot[19]: 0x0
      totf[19]: 0x0
      tot_overflow[19]: 0x0
      toa_busy[19]: 0x0
      toa_ready[19]: 0x0
      tot_busy[19]: 0x0
      tot_ready[19]: 0x0
      en_read[19]: 0x0
      probe_pa[20]: 0x0
      probe_vthc[20]: 0x0
      probe_dig_out_disc[20]: 0x0
      probe_toa[20]: 0x0
      probe_tot[20]: 0x0
      totf[20]: 0x0
      tot_overflow[20]: 0x0
      toa_busy[20]: 0x0
      toa_ready[20]: 0x0
      tot_busy[20]: 0x0
      tot_ready[20]: 0x0
      en_read[20]: 0x0
      probe_pa[21]: 0x0
      probe_vthc[21]: 0x0
      probe_dig_out_disc[21]: 0x0
      probe_toa[21]: 0x0
      probe_tot[21]: 0x0
      totf[21]: 0x0
      tot_overflow[21]: 0x0
      toa_busy[21]: 0x0
      toa_ready[21]: 0x0
      tot_busy[21]: 0x0
      tot_ready[21]: 0x0
      en_read[21]: 0x0
      probe_pa[22]: 0x0
      probe_vthc[22]: 0x0
      probe_dig_out_disc[22]: 0x0
      probe_toa[22]: 0x0
      probe_tot[22]: 0x0
      totf[22]: 0x0
      tot_overflow[22]: 0x0
      toa_busy[22]: 0x0
      toa_ready[22]: 0x0
      tot_busy[22]: 0x0
      tot_ready[22]: 0x0
      en_read[22]: 0x0
      probe_pa[23]: 0x0
      probe_vthc[23]: 0x0
      probe_dig_out_disc[23]: 0x0
      probe_toa[23]: 0x0
      probe_tot[23]: 0x0
      totf[23]: 0x0
      tot_overflow[23]: 0x0
      toa_busy[23]: 0x0
      toa_ready[23]: 0x0
      tot_busy[23]: 0x0
      tot_ready[23]: 0x0
      en_read[23]: 0x0
      probe_pa[24]: 0x0
      probe_vthc[24]: 0x0
      probe_dig_out_disc[24]: 0x0
      probe_toa[24]: 0x0
      probe_tot[24]: 0x0
      totf[24]: 0x0
      tot_overflow[24]: 0x0
      toa_busy[24]: 0x0
      toa_ready[24]: 0x0
      tot_busy[24]: 0x0
      tot_ready[24]: 0x0
      en_read[24]: 0x0
      rstL: 0x1
    RENABLE: 0x0
    RSTB_RAM: 0x1
    RSTB_READ: 0x1
    RSTB_TDC: 0x1
    RSTB_COUNTER: 0x1
    CK_WRITE: Disabled
    DeserSampleEdge: RisingEdge
    EmuEnable: 0x0
    RunEnable: 0x1
    PulseCount: 0x1
    PulseWidth: 0x7d0
    PulsePeriod: 0xfa0
    Continuous: 0x1
