Top:
  Fpga[:]: # "[:]" is a wildcard for a dict search
    Asic:
      SlowControl:
        dac: 0x0
        ON_dac_LR: 0x1
        Write_opt: 0x0
        Precharge_opt: 0x0
        ref_bg: 0x1
        dac_pulser: 0x7
        Ccomp_TZ: 0x0
        Rin_Vpa: 0x0
        Cp_Vpa: 0x0
        dac_biaspa: 0x10
        ON_dac_biaspa: 0x1
        ON_ota_dac: 0x1
        DAC10bit: 0x173
        SatFVa: 0x3
        IntFVa: 0x1
        SatFTz: 0x4
        IntFTz: 0x1
        totf_satovfw: 0x1
        totc_satovfw: 0x1
        toa_satovfw: 0x1
        # ckw_choice: 0x0
        Ck40_choice: 0x0
        cBitf: 0x0
        DLL_ALockR_en: 0x1
        CP_b: 0x5
        ext_Vcrtlf_en: 0x0
        cBits: 0xf
        ext_Vcrtls_en: 0x1
        cBitc: 0xf
        ext_Vcrtlc_en: 0x0
        en_8drivers: 0x0
        EN_ck_SRAM[0]: 0x1
        ON_Ctest[0]: 0x0
        disable_pa[0]: 0x1
        bit_vth_cor[0]: 0x8
        ON_discri[0]: 0x0
        EN_hyst[0]: 0x1
        EN_trig_ext[0]: 0x0
        cBit_f_TOT[0]: 0x0
        cBit_c_TOT[0]: 0x0
        cBit_s_TOT[0]: 0x0
        cBit_s_TOA[0]: 0x0
        cBit_f_TOA[0]: 0x0
        EN_ck_SRAM[1]: 0x1
        ON_Ctest[1]: 0x0
        disable_pa[1]: 0x1
        bit_vth_cor[1]: 0x8
        ON_discri[1]: 0x0
        EN_hyst[1]: 0x1
        EN_trig_ext[1]: 0x0
        cBit_f_TOT[1]: 0x0
        cBit_c_TOT[1]: 0x0
        cBit_s_TOT[1]: 0x0
        cBit_s_TOA[1]: 0x0
        cBit_f_TOA[1]: 0x0
        EN_ck_SRAM[2]: 0x1
        ON_Ctest[2]: 0x0
        disable_pa[2]: 0x1
        bit_vth_cor[2]: 0x8
        ON_discri[2]: 0x0
        EN_hyst[2]: 0x1
        EN_trig_ext[2]: 0x0
        cBit_f_TOT[2]: 0x0
        cBit_c_TOT[2]: 0x0
        cBit_s_TOT[2]: 0x0
        cBit_s_TOA[2]: 0x0
        cBit_f_TOA[2]: 0x0
        EN_ck_SRAM[3]: 0x1
        ON_Ctest[3]: 0x0
        disable_pa[3]: 0x1
        bit_vth_cor[3]: 0x8
        ON_discri[3]: 0x0
        EN_hyst[3]: 0x1
        EN_trig_ext[3]: 0x0
        cBit_f_TOT[3]: 0x0
        cBit_c_TOT[3]: 0x0
        cBit_s_TOT[3]: 0x0
        cBit_s_TOA[3]: 0x0
        cBit_f_TOA[3]: 0x0
        EN_ck_SRAM[4]: 0x1
        ON_Ctest[4]: 0x1
        disable_pa[4]: 0x0
        bit_vth_cor[4]: 0x40
        ON_discri[4]: 0x1
        EN_hyst[4]: 0x1
        EN_trig_ext[4]: 0x0
        cBit_f_TOT[4]: 0xf
        cBit_c_TOT[4]: 0xf
        cBit_s_TOT[4]: 0x0
        cBit_s_TOA[4]: 0x0
        cBit_f_TOA[4]: 0x0
        EN_ck_SRAM[5]: 0x1
        ON_Ctest[5]: 0x0
        disable_pa[5]: 0x1
        bit_vth_cor[5]: 0x8
        ON_discri[5]: 0x0
        EN_hyst[5]: 0x1
        EN_trig_ext[5]: 0x0
        cBit_f_TOT[5]: 0x0
        cBit_c_TOT[5]: 0x0
        cBit_s_TOT[5]: 0x0
        cBit_s_TOA[5]: 0x0
        cBit_f_TOA[5]: 0x0
        EN_ck_SRAM[6]: 0x1
        ON_Ctest[6]: 0x0
        disable_pa[6]: 0x1
        bit_vth_cor[6]: 0x8
        ON_discri[6]: 0x0
        EN_hyst[6]: 0x1
        EN_trig_ext[6]: 0x0
        cBit_f_TOT[6]: 0x0
        cBit_c_TOT[6]: 0x0
        cBit_s_TOT[6]: 0x0
        cBit_s_TOA[6]: 0x0
        cBit_f_TOA[6]: 0x0
        EN_ck_SRAM[7]: 0x1
        ON_Ctest[7]: 0x0
        disable_pa[7]: 0x1
        bit_vth_cor[7]: 0x8
        ON_discri[7]: 0x0
        EN_hyst[7]: 0x1
        EN_trig_ext[7]: 0x0
        cBit_f_TOT[7]: 0x0
        cBit_c_TOT[7]: 0x0
        cBit_s_TOT[7]: 0x0
        cBit_s_TOA[7]: 0x0
        cBit_f_TOA[7]: 0x0
        EN_ck_SRAM[8]: 0x1
        ON_Ctest[8]: 0x0
        disable_pa[8]: 0x1
        bit_vth_cor[8]: 0x8
        ON_discri[8]: 0x0
        EN_hyst[8]: 0x1
        EN_trig_ext[8]: 0x0
        cBit_f_TOT[8]: 0x0
        cBit_c_TOT[8]: 0x0
        cBit_s_TOT[8]: 0x0
        cBit_s_TOA[8]: 0x0
        cBit_f_TOA[8]: 0x0
        EN_ck_SRAM[9]: 0x1
        ON_Ctest[9]: 0x0
        disable_pa[9]: 0x1
        bit_vth_cor[9]: 0x8
        ON_discri[9]: 0x0
        EN_hyst[9]: 0x1
        EN_trig_ext[9]: 0x0
        cBit_f_TOT[9]: 0x0
        cBit_c_TOT[9]: 0x0
        cBit_s_TOT[9]: 0x0
        cBit_s_TOA[9]: 0x0
        cBit_f_TOA[9]: 0x0
        EN_ck_SRAM[10]: 0x1
        ON_Ctest[10]: 0x0
        disable_pa[10]: 0x1
        bit_vth_cor[10]: 0x8
        ON_discri[10]: 0x0
        EN_hyst[10]: 0x1
        EN_trig_ext[10]: 0x0
        cBit_f_TOT[10]: 0x0
        cBit_c_TOT[10]: 0x0
        cBit_s_TOT[10]: 0x0
        cBit_s_TOA[10]: 0x0
        cBit_f_TOA[10]: 0x0
        EN_ck_SRAM[11]: 0x1
        ON_Ctest[11]: 0x0
        disable_pa[11]: 0x1
        bit_vth_cor[11]: 0x8
        ON_discri[11]: 0x0
        EN_hyst[11]: 0x1
        EN_trig_ext[11]: 0x0
        cBit_f_TOT[11]: 0x0
        cBit_c_TOT[11]: 0x0
        cBit_s_TOT[11]: 0x0
        cBit_s_TOA[11]: 0x0
        cBit_f_TOA[11]: 0x0
        EN_ck_SRAM[12]: 0x1
        ON_Ctest[12]: 0x0
        disable_pa[12]: 0x1
        bit_vth_cor[12]: 0x8
        ON_discri[12]: 0x0
        EN_hyst[12]: 0x1
        EN_trig_ext[12]: 0x0
        cBit_f_TOT[12]: 0x0
        cBit_c_TOT[12]: 0x0
        cBit_s_TOT[12]: 0x0
        cBit_s_TOA[12]: 0x0
        cBit_f_TOA[12]: 0x0
        EN_ck_SRAM[13]: 0x1
        ON_Ctest[13]: 0x0
        disable_pa[13]: 0x1
        bit_vth_cor[13]: 0x8
        ON_discri[13]: 0x0
        EN_hyst[13]: 0x1
        EN_trig_ext[13]: 0x0
        cBit_f_TOT[13]: 0x0
        cBit_c_TOT[13]: 0x0
        cBit_s_TOT[13]: 0x0
        cBit_s_TOA[13]: 0x0
        cBit_f_TOA[13]: 0x0
        EN_ck_SRAM[14]: 0x1
        ON_Ctest[14]: 0x0
        disable_pa[14]: 0x1
        bit_vth_cor[14]: 0x8
        ON_discri[14]: 0x0
        EN_hyst[14]: 0x1
        EN_trig_ext[14]: 0x0
        cBit_f_TOT[14]: 0x0
        cBit_c_TOT[14]: 0x0
        cBit_s_TOT[14]: 0x0
        cBit_s_TOA[14]: 0x0
        cBit_f_TOA[14]: 0x0
        EN_ck_SRAM[15]: 0x1
        ON_Ctest[15]: 0x0
        disable_pa[15]: 0x1
        bit_vth_cor[15]: 0x8
        ON_discri[15]: 0x0
        EN_hyst[15]: 0x1
        EN_trig_ext[15]: 0x0
        cBit_f_TOT[15]: 0x0
        cBit_c_TOT[15]: 0x0
        cBit_s_TOT[15]: 0x0
        cBit_s_TOA[15]: 0x0
        cBit_f_TOA[15]: 0x0
        EN_ck_SRAM[16]: 0x1
        ON_Ctest[16]: 0x0
        disable_pa[16]: 0x1
        bit_vth_cor[16]: 0x8
        ON_discri[16]: 0x0
        EN_hyst[16]: 0x1
        EN_trig_ext[16]: 0x0
        cBit_f_TOT[16]: 0x0
        cBit_c_TOT[16]: 0x0
        cBit_s_TOT[16]: 0x0
        cBit_s_TOA[16]: 0x0
        cBit_f_TOA[16]: 0x0
        EN_ck_SRAM[17]: 0x1
        ON_Ctest[17]: 0x0
        disable_pa[17]: 0x1
        bit_vth_cor[17]: 0x8
        ON_discri[17]: 0x0
        EN_hyst[17]: 0x1
        EN_trig_ext[17]: 0x0
        cBit_f_TOT[17]: 0x0
        cBit_c_TOT[17]: 0x0
        cBit_s_TOT[17]: 0x0
        cBit_s_TOA[17]: 0x0
        cBit_f_TOA[17]: 0x0
        EN_ck_SRAM[18]: 0x1
        ON_Ctest[18]: 0x0
        disable_pa[18]: 0x1
        bit_vth_cor[18]: 0x8
        ON_discri[18]: 0x0
        EN_hyst[18]: 0x1
        EN_trig_ext[18]: 0x0
        cBit_f_TOT[18]: 0x0
        cBit_c_TOT[18]: 0x0
        cBit_s_TOT[18]: 0x0
        cBit_s_TOA[18]: 0x0
        cBit_f_TOA[18]: 0x0
        EN_ck_SRAM[19]: 0x1
        ON_Ctest[19]: 0x0
        disable_pa[19]: 0x1
        bit_vth_cor[19]: 0x8
        ON_discri[19]: 0x0
        EN_hyst[19]: 0x1
        EN_trig_ext[19]: 0x0
        cBit_f_TOT[19]: 0x0
        cBit_c_TOT[19]: 0x0
        cBit_s_TOT[19]: 0x0
        cBit_s_TOA[19]: 0x0
        cBit_f_TOA[19]: 0x0
        EN_ck_SRAM[20]: 0x1
        ON_Ctest[20]: 0x0
        disable_pa[20]: 0x1
        bit_vth_cor[20]: 0x8
        ON_discri[20]: 0x0
        EN_hyst[20]: 0x1
        EN_trig_ext[20]: 0x0
        cBit_f_TOT[20]: 0x0
        cBit_c_TOT[20]: 0x0
        cBit_s_TOT[20]: 0x0
        cBit_s_TOA[20]: 0x0
        cBit_f_TOA[20]: 0x0
        EN_ck_SRAM[21]: 0x1
        ON_Ctest[21]: 0x0
        disable_pa[21]: 0x1
        bit_vth_cor[21]: 0x8
        ON_discri[21]: 0x0
        EN_hyst[21]: 0x1
        EN_trig_ext[21]: 0x0
        cBit_f_TOT[21]: 0x0
        cBit_c_TOT[21]: 0x0
        cBit_s_TOT[21]: 0x0
        cBit_s_TOA[21]: 0x0
        cBit_f_TOA[21]: 0x0
        EN_ck_SRAM[22]: 0x1
        ON_Ctest[22]: 0x0
        disable_pa[22]: 0x1
        bit_vth_cor[22]: 0x8
        ON_discri[22]: 0x0
        EN_hyst[22]: 0x1
        EN_trig_ext[22]: 0x0
        cBit_f_TOT[22]: 0x0
        cBit_c_TOT[22]: 0x0
        cBit_s_TOT[22]: 0x0
        cBit_s_TOA[22]: 0x0
        cBit_f_TOA[22]: 0x0
        EN_ck_SRAM[23]: 0x1
        ON_Ctest[23]: 0x0
        disable_pa[23]: 0x1
        bit_vth_cor[23]: 0x8
        ON_discri[23]: 0x0
        EN_hyst[23]: 0x1
        EN_trig_ext[23]: 0x0
        cBit_f_TOT[23]: 0x0
        cBit_c_TOT[23]: 0x0
        cBit_s_TOT[23]: 0x0
        cBit_s_TOA[23]: 0x0
        cBit_f_TOA[23]: 0x0
        EN_ck_SRAM[24]: 0x0
        ON_Ctest[24]: 0x0
        disable_pa[24]: 0x1
        bit_vth_cor[24]: 0x0
        ON_discri[24]: 0x0
        EN_hyst[24]: 0x0
        EN_trig_ext[24]: 0x0
        cBit_f_TOT[24]: 0x0
        cBit_c_TOT[24]: 0x0
        cBit_s_TOT[24]: 0x0
        cBit_s_TOA[24]: 0x0
        cBit_f_TOA[24]: 0x0
        cd[0]: 0x6
        cd[1]: 0x0
        cd[2]: 0x0
        cd[3]: 0x0
        cd[4]: 0x0
        PLL: 0x1
        dac_icpb: 0xa
        # dac_CP_BWb: 0x20 # Legacy V1 value
        Shifted_ck40: 0x1
        dac_CP_BWb: 0x10 # V2 maps dac_CP_BW<0> to Shifted_ck40
        EN_Ext_Vin_VCO: 0x0
        setN: 0x3
        setProbe: 0x0
        EN_500: 0x0
        EN_1000: 0x0
        EN_2000: 0x1
        EN_4000: 0x0
        EN_200p: 0x0
        EN_LowKvco: 0x0
        delay: 0x0
        Ph: 0x0
        forcedown: 0x0
        inita: 0x1
        initb: 0x1
        initc: 0x1
        cpen: 0x1
        cp: 0x0
        En_40M: 0x1
        En_640M: 0x1
        rstL: 0x1
